### ISSUE TITLE
Create a wireframe and design for the website

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#63]

**Comment by LuandaS** [comment]
![MarketPlace](https://user-images.githubusercontent.com/113204714/225796810-2c6876b9-f34b-4e59-a841-cda9414509b1.png)
![itemPage](https://user-images.githubusercontent.com/113204714/225796831-b7c52d24-e44e-4571-99fc-b5c8465287db.png)
![profilePage](https://user-images.githubusercontent.com/113204714/225796866-b41151ec-6436-42f7-9608-84305afd2d7d.png)


Market Place, Profile Page, Item Page
